(****************************************************************************


golibcod.pas

produced by Borland Resource Workshop


*****************************************************************************)

unit glb8cod;

{$D-}
{$L-}

interface

const

	CloseButton_P	=	10001;
	CloseButton_R	=	10002;
	ReduceButton_R	=	10004;
	UnzoomButton_P	=	10005;
	UnzoomButton_R	=	10006;
	ZoomButton_P	=	10007;
	ZoomButton_R	=	10008;
	FrecciaDestra_R	=	10009;
	FrecciaDestra_P	=	10010;
	FrecciaSinistra_R	=	10011;
	FrecciaSinistra_P	=	10012;
	FrecciaSopra_R	=	10013;
	FrecciaSopra_P	=	10014;
	FrecciaSotto_R	=	10015;
	FrecciaSotto_P	=	10016;
	ReduceButton_P	=	10003;
	ReduceButton_D	=	10017;
	UnzoomButton_D	=	10018;
	ZoomButton_D	=	10019;
	FrecciaDestra_D	=	10020;
	FrecciaSinistra_D	=	10021;
	FrecciaSopra_D	=	10022;
	FrecciaSotto_D	=	10023;
	NumeroRisorse	=	36;
	OtherButtons	=	10024;
	WindowIcon	=	19900;
	HelpButton_R	=	1;
	HelpButton_P	=	2;
	HelpButton_D	=	3;
	CloseButton_D	=	4;
	PullDown1_R	=	10025;
	PullDown1_P	=	10026;
	PullDown1_D	=	10027;
	PullDown2_R	=	10028;
	PullDown2_P	=	10029;
	PullDown2_D	=	10030;
	ResizeIcon	=	10031;
implementation

end.
