(****************************************************************************


golibcod.pas

produced by Borland Resource Workshop


*****************************************************************************)

unit golibcod;

{ by Ernesto CIANCIOTTA Productions }
{$D-}
{$L-}

interface

const

	CloseButton_P	=	10001;
	CloseButton_R	=	10002;
	NumeroRisorse	=	12;
	OtherButtons	=	7;
	WindowIcon	=	19900;
	CloseButton_D	=	10000;
	ResizeIcon	=	10031;
	Arrows	=	5;
	ReduceBtn	=	1;
	HelpBtn	=	4;
	ZoomBtn	=	2;
	UnzoomBtn	=	3;
	PullBtns	=	6;
implementation

end.
