(****************************************************************************


t_barcod.pas

produced by Borland Resource Workshop


*****************************************************************************)

unit t_barcod;

interface

const

	Matita_R	=	1;
	Matita_P	=	2;
	Documento_R	=	3;
	Documento_P	=	4;
	Vuoto_R	=	5;
	Vuoto_P	=	6;
	Paint_R	=	7;
	Paint_P	=	8;
	NumeroBitmaps	=	26;
	Cascata_R	=	9;
	Cascata_P	=	10;
	LeftToolBar_R	=	11;
	LeftToolBar_P	=	12;
	RigthToolBar_R	=	13;
	RigthToolBar_P	=	14;
	RigthToolBar_D	=	25;
	LeftToolBar_D	=	26;
implementation

end.
