(****************************************************************************


files.pas

produced by Borland Resource Workshop


*****************************************************************************)

unit files;

interface

const

	Exe_File_Icon	=	20001;
	Doc_Icon	=	20002;
	Any_File_Icon	=	20003;
	Directory_Icon	=	20004;
	Hide_File_Icon	=	20005;
	Sys_File_Icon	=	20006;
implementation

end.
