(****************************************************************************


roma.pas

produced by Borland Resource Workshop


*****************************************************************************)

unit roma;

interface

const

	Lettera_R	=	1000;
	Lettera_O	=	1001;
	Lettera_M	=	1002;
	Lettera_A	=	1003;
	Punto_Esclamativo	=	1004;
	Lavinia	=	2000;
	Gloria	=	2001;
	Cristina	=	2002;
	Laura	=	2003;
	Federica	=	2004;
implementation

end.
